version: '2'
services:
    pinder_server:
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - ./server:/usr/src/app/server
        ports:
        - "3000:3000"
        links:
            - db
        env_file: 
            - .env
    db:
        build: ./database
        restart: always
        ports: 
            - "3306:3306"
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8081:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        depends_on:
            - db
    